package ooad;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author DELL
 */

public class HoaDonForm extends javax.swing.JFrame {

    /**
     * Creates new form HoaDonForm
     */
    public HoaDonForm() {
        initComponents();
        setLocationRelativeTo(null);
        show_jtable_hoadon();
    }
    public Connection getConnection() throws SQLException{
        Connection conn = null;
        conn = DriverManager.getConnection("jdbc:mysql://localhost/store","root","");
        return conn;
    }
    public ArrayList<HoaDon> getHoadonList(){
        ArrayList<HoaDon> hoadonList = new ArrayList<HoaDon>();
        HoaDon hoaDon;
        try {
            Connection con = getConnection();
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("SELECT * FROM hoadon");
            while(rs.next()){
                hoaDon = new HoaDon(rs.getString("ma_hd"), rs.getInt("ma_sp"), rs.getFloat("gia_sp"), rs.getInt("so_luong"),rs.getFloat("tong_tien"),rs.getString("ngay_ban"));
                hoadonList.add(hoaDon);
            } 
        } catch (SQLException ex) {
            Logger.getLogger(HoaDonForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        return hoadonList;
    }
    public void show_jtable_hoadon(){
        ArrayList<HoaDon> list = getHoadonList();
        DefaultTableModel model = (DefaultTableModel) jtable_hoadon.getModel();
        
        model.setRowCount(0);
        Object[] row = new Object[6];
        for(int i=0;i<list.size();i++){
            row[0] = list.get(i).getMahd();
            row[1] = list.get(i).getMasp();
            row[2] = list.get(i).getGiasp();
            row[3] = list.get(i).getSoluong();
            row[4] = list.get(i).getTongtien();
            row[5] = list.get(i).getNgayban();
            model.addRow(row);
        }
    }
    public  void showItem(int index){
        txtMahd.setText(getHoadonList().get(index).getMahd());
        txtMasp.setText(Integer.toString(getHoadonList().get(index).getMasp()));
        btnGetGiasp.setText(Float.toString(getHoadonList().get(index).getGiasp()));
        txtSoluong.setText(Integer.toString(getHoadonList().get(index).getSoluong()));
        btnTinhtien.setText(Float.toString(getHoadonList().get(index).getTongtien()));
        try {
            Date date = new SimpleDateFormat("dd-MM-yyyy").parse(getHoadonList().get(index).getNgayban());
            txtNgayban.setDate(date);
        } catch (ParseException ex) {
            Logger.getLogger(NhapHangForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtable_hoadon = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtMahd = new javax.swing.JTextField();
        txtMasp = new javax.swing.JTextField();
        txtSoluong = new javax.swing.JTextField();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        cbbGiamgia = new javax.swing.JComboBox<>();
        btnTinhtien = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        btnGetGiasp = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtNgayban = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Netbean\\Codejava\\OOAD\\icon\\back.png")); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        jtable_hoadon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Mã hóa đơn", "Mã sản phẩm", "Giá sản phẩm", "Số lượng", "Tổng tiền", "Ngày bán"
            }
        ));
        jtable_hoadon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtable_hoadonMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtable_hoadon);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel2.setText("Mã sản phẩm");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel3.setText("Mã hóa đơn");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel5.setText("Số lượng");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel6.setText("Tổng tiền");

        txtMasp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaspActionPerformed(evt);
            }
        });

        btnThem.setText("Thêm");
        btnThem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnThemMouseClicked(evt);
            }
        });
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnSua.setText("Sửa");
        btnSua.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSuaMouseClicked(evt);
            }
        });
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnXoa.setText("Xóa");
        btnXoa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnXoaMouseClicked(evt);
            }
        });

        jButton4.setText("In hóa đơn");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });

        cbbGiamgia.setBackground(new java.awt.Color(255, 255, 204));
        cbbGiamgia.setForeground(new java.awt.Color(51, 153, 0));
        cbbGiamgia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "30%", "50%" }));

        btnTinhtien.setBackground(new java.awt.Color(204, 255, 204));
        btnTinhtien.setFont(new java.awt.Font("Segoe UI", 3, 17)); // NOI18N
        btnTinhtien.setForeground(new java.awt.Color(255, 51, 255));
        btnTinhtien.setText("Tổng số tiền");
        btnTinhtien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTinhtienMouseClicked(evt);
            }
        });
        btnTinhtien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTinhtienActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel7.setText("Giảm giá");

        btnGetGiasp.setBackground(new java.awt.Color(204, 255, 204));
        btnGetGiasp.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        btnGetGiasp.setForeground(new java.awt.Color(51, 51, 255));
        btnGetGiasp.setText("Xem giá sp");
        btnGetGiasp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGetGiaspMouseClicked(evt);
            }
        });
        btnGetGiasp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGetGiaspActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 0, 255));
        jLabel8.setText("VNĐ");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 255));
        jLabel9.setText("VNĐ");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel4.setText("Giá sản phẩm");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel10.setText("Ngày bán");

        txtNgayban.setDateFormatString("dd-MM-yyyy");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtMahd, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(cbbGiamgia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtSoluong, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(btnTinhtien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtNgayban, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnGetGiasp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtMasp, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE))))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 665, Short.MAX_VALUE)
                        .addComponent(jButton4)
                        .addGap(27, 27, 27))))
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(btnThem)
                .addGap(26, 26, 26)
                .addComponent(btnSua)
                .addGap(18, 18, 18)
                .addComponent(btnXoa)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 455, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMahd, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtMasp, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnGetGiasp, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSoluong, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbbGiamgia, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnTinhtien, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNgayban, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnThem)
                            .addComponent(btnSua)
                            .addComponent(btnXoa))
                        .addGap(19, 19, 19))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnThemActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        this.setVisible(false);
        new MenuForm().setVisible(true);
    }//GEN-LAST:event_jLabel1MouseClicked

    // truyen du lieu sang in hoa don
    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        TruyenHD thd = new TruyenHD();
        thd.setMahd(txtMahd.getText());
        thd.setMasp(txtMasp.getText());
        thd.setSoluong(txtSoluong.getText());
        thd.setTongtien(btnTinhtien.getText());
        new InhoadonForm().setVisible(true);
    }//GEN-LAST:event_jButton4MouseClicked

    public boolean updateSoluongSanPham() throws SQLException{
        int numNew = Integer.parseInt(txtSoluong.getText());
        int numOld = 0;
        Connection con = getConnection();
        PreparedStatement ps = con.prepareStatement("SELECT * FROM sanpham WHERE ma_sp='"+txtMasp.getText()+"'");            
        ResultSet rs = ps.executeQuery();
        if(rs.next()){
            numOld = Integer.parseInt( rs.getString("so_luong"));
        }else{
            JOptionPane.showMessageDialog(null, "Mã sản phẩm không tồn tại");
        }
        
        if ((numOld- numNew) >= 0) {
            PreparedStatement ps2 = con.prepareStatement("UPDATE sanpham SET so_luong = '"+(numOld-numNew)+"' WHERE ma_sp='"+txtMasp.getText()+"'");
            ps2.executeUpdate();
            return true;
        
        }else if((numOld - numNew) < 0){
            return false;
        }
        return false;
    }
    
    private void btnThemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThemMouseClicked
        if (txtMahd != null && txtMasp.getText() != null && txtSoluong.getText() != null) {
            try {
                if (updateSoluongSanPham()) {
                    Connection con = getConnection();
                    PreparedStatement ps = con.prepareStatement("INSERT INTO hoadon(ma_hd, ma_sp, gia_sp, so_luong, tong_tien,ngay_ban) VALUES (?,?,?,?,?,?)");
                    ps.setString(1, txtMahd.getText());
                    ps.setString(2, txtMasp.getText());
                    ps.setString(3, btnGetGiasp.getText());
                    ps.setString(4, txtSoluong.getText());
                    ps.setString(5, btnTinhtien.getText());
                    
                    SimpleDateFormat dateFormat = new SimpleDateFormat("dd-MM-yyyy");
                    String date = dateFormat.format(txtNgayban.getDate());
                    ps.setString(6, date);
                
                    ps.executeUpdate();
                    show_jtable_hoadon();
                
                    JOptionPane.showMessageDialog(null, "Xong");
                }else{
                    JOptionPane.showMessageDialog(null, "Số lượng sản phẩm trong cửa hàng không đủ\n Vui lòng xem lại");
                }

            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage());
            }
        }else{
            JOptionPane.showMessageDialog(null, "Vui lòng điền đủ thông tin");
        }
    }//GEN-LAST:event_btnThemMouseClicked

    private void btnGetGiaspActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGetGiaspActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGetGiaspActionPerformed

    private void btnGetGiaspMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGetGiaspMouseClicked
        
        
        try {
            Connection con = getConnection();
            
            PreparedStatement ps = con.prepareStatement("SELECT * FROM sanpham WHERE ma_sp='"+txtMasp.getText()+"'");            
            ResultSet rs = ps.executeQuery();
            if(rs.next()){
                btnGetGiasp.setText(rs.getString("gia_ban"));
            }else{
                JOptionPane.showMessageDialog(null, "Mã sản phẩm không tồn tại");
            }
            
            
        } catch (SQLException ex) {
            Logger.getLogger(HoaDonForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnGetGiaspMouseClicked

    // Tính tổng tiền sản phẩm
    private void btnTinhtienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTinhtienMouseClicked
       float don_gia = Float.parseFloat(btnGetGiasp.getText());
       int soluong = Integer.parseInt(txtSoluong.getText());
       float tongtien = 0;
       String cbb = (String) cbbGiamgia.getSelectedItem();
        if (cbb=="0") {
            tongtien = don_gia * soluong;
        }else if (cbb == "30%") {
            tongtien = don_gia * soluong * 7/10;
        }else if (cbb == "50%") {
            tongtien = don_gia * soluong/2;
        }
        btnTinhtien.setText(String.valueOf(tongtien));
        
    }//GEN-LAST:event_btnTinhtienMouseClicked

    private void btnTinhtienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTinhtienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTinhtienActionPerformed

    private void jtable_hoadonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtable_hoadonMouseClicked
        int index = jtable_hoadon.getSelectedRow();
        showItem(index);
    }//GEN-LAST:event_jtable_hoadonMouseClicked

    private void btnSuaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSuaMouseClicked
        if (txtMahd != null) {
            try {
                Connection con = getConnection();
                PreparedStatement ps = con.prepareStatement("UPDATE hoadon SET ma_sp=?,so_luong=?,ngay_ban=? WHERE ma_hd=? ");
                ps.setString(1, txtMasp.getText());
                ps.setString(2, txtSoluong.getText());
                
                
                 SimpleDateFormat dateFormat = new SimpleDateFormat("dd-MM-yyyy");
                 String date = dateFormat.format(txtNgayban.getDate());
                 ps.setString(3, date);
                 
                 ps.setString(4, txtMahd.getText());
                
                ps.executeUpdate();
                show_jtable_hoadon();
                JOptionPane.showMessageDialog(null, "Xong");
            } catch (SQLException ex) {
                Logger.getLogger(HoaDonForm.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else{
            JOptionPane.showMessageDialog(null, "Wrong");
        }
    }//GEN-LAST:event_btnSuaMouseClicked

    private void btnXoaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnXoaMouseClicked
        if (txtMahd !=null) {
            try {
                Connection con = getConnection();
                PreparedStatement ps = con.prepareStatement("DELETE FROM hoadon WHERE ma_hd=? ");
                ps.setString(1, txtMahd.getText());
                ps.executeUpdate();
                show_jtable_hoadon();
                JOptionPane.showMessageDialog(null, "Deleted");
            } catch (SQLException ex) {
                Logger.getLogger(HoaDonForm.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else{
            JOptionPane.showMessageDialog(null, "wrong");
        }
    }//GEN-LAST:event_btnXoaMouseClicked

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSuaActionPerformed

    private void txtMaspActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaspActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaspActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HoaDonForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HoaDonForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HoaDonForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HoaDonForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HoaDonForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGetGiasp;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnTinhtien;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> cbbGiamgia;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtable_hoadon;
    private javax.swing.JTextField txtMahd;
    private javax.swing.JTextField txtMasp;
    private com.toedter.calendar.JDateChooser txtNgayban;
    private javax.swing.JTextField txtSoluong;
    // End of variables declaration//GEN-END:variables
}
