package ooad;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.PrintWriter;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


// thu vien excel
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.CellType;
import org.apache.poi.xssf.usermodel.XSSFRow;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

/**
 *
 * @author DELL
 */
public class ThongKeForm extends javax.swing.JFrame {

    /**
     * Creates new form ThongKeForm
     */
    public ThongKeForm() {
        initComponents();
        setLocationRelativeTo(null);
        show_jtable_Nhaphang();
        show_jtable_hoadon();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        table_nhaphang = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        table_banhang = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        txtThang = new javax.swing.JTextField();
        search_nhap = new javax.swing.JButton();
        search_ban = new javax.swing.JButton();
        in_dsban = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        table_nhaphang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã sản phẩm", "Tên sản phẩm", "Giá nhập", "Số lượng", "Ngày về"
            }
        ));
        jScrollPane1.setViewportView(table_nhaphang);

        table_banhang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Mã hóa đơn", "Mã sản phẩm", "Giá sản phẩm", "Số lượng", "Tổng tiền", "Ngày bán"
            }
        ));
        jScrollPane2.setViewportView(table_banhang);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Nhập hàng");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Bán hàng");

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Netbean\\Codejava\\OOAD\\icon\\back.png")); // NOI18N
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        jButton1.setText("In");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        txtThang.setText("tháng");

        search_nhap.setText("Tìm");
        search_nhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_nhapActionPerformed(evt);
            }
        });

        search_ban.setText("Tìm");
        search_ban.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_banActionPerformed(evt);
            }
        });

        in_dsban.setText("In");
        in_dsban.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                in_dsbanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 567, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(119, 119, 119)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(448, 448, 448)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(134, 134, 134)
                .addComponent(search_nhap)
                .addGap(27, 27, 27)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(159, 159, 159)
                .addComponent(txtThang, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(search_ban)
                .addGap(37, 37, 37)
                .addComponent(in_dsban, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(191, 191, 191))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jLabel2))
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(txtThang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(search_nhap)
                    .addComponent(search_ban)
                    .addComponent(in_dsban))
                .addGap(45, 45, 45))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
       this.setVisible(false);
       new MenuForm().setVisible(true);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        
        XSSFWorkbook workbook = new XSSFWorkbook();
        XSSFSheet sheet=workbook.createSheet("danhsachnhaphang");
        XSSFRow row = null ;
        Cell cell=null ;
        // lui xuong 3 hang
        
        
        row = sheet.createRow(3);
        
        cell = row.createCell(0, CellType.STRING);
        cell.setCellValue("Mã sản phẩm");
        
        cell = row.createCell(1, CellType.STRING);
        cell.setCellValue("Tên sản phẩm");
        
        cell = row.createCell(2, CellType.STRING);
        cell.setCellValue("Giá nhập");
        
        cell = row.createCell(3, CellType.STRING);
        cell.setCellValue("Số lượng");
        
        cell = row.createCell(4, CellType.STRING);
        cell.setCellValue("Ngày về");
        
        
        for (int i = 0; i<getNhaphangList().size() ; i++) {
            // bat dau tu dong thu 4
            row = sheet.createRow(4+i);
            
            cell=row.createCell(0,CellType.NUMERIC);
            cell.setCellValue(getNhaphangList().get(i).getMasp());
            
            cell=row.createCell(1,CellType.STRING);
            cell.setCellValue(getNhaphangList().get(i).getTensp());
            
            cell=row.createCell(2,CellType.STRING);
            cell.setCellValue(getNhaphangList().get(i).getGianhap());
            
            cell=row.createCell(3,CellType.STRING);
            cell.setCellValue(getNhaphangList().get(i).getSoluong());
            
            cell=row.createCell(4,CellType.STRING);
            cell.setCellValue(getNhaphangList().get(i).getNgayveString());
        }
        
        File f = new File("D://danhsachnhaphang.xlsx");
        if (!f.exists()) {
            try {
                f.createNewFile();
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage());
            }
        }
        FileOutputStream fos;
        try {
            fos = new FileOutputStream(f);
            workbook.write(fos);
            workbook.close();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(ThongKeForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(ThongKeForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        JOptionPane.showMessageDialog(null, "Xong!");
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void search_nhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_nhapActionPerformed
        String Mon = "-"+txtThang.getText()+"-";
        Nhaphang nhaphang;
        ArrayList<Nhaphang> list = new ArrayList<Nhaphang>();
        try {
            Connection con =getConnection();
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("SELECT * FROM nhaphang WHERE ngay_ve LIKE '%"+Mon+"%'");
            while(rs.next()){
                nhaphang = new Nhaphang(rs.getInt("stt"),rs.getInt("ma_sp"), rs.getString("ten_sp"), rs.getFloat("gia_nhap"), rs.getInt("so_luong"), rs.getString("ngay_ve"));
                list.add(nhaphang);
                
                DefaultTableModel model = (DefaultTableModel) table_nhaphang.getModel();
                model.setRowCount(0);
                Object[] row = new Object[6];
                    for(int i=0; i<list.size();i++){
                        row[0] = list.get(i).getMasp();
                        row[1] = list.get(i).getTensp();
                        row[2] = list.get(i).getGianhap();
                        row[3] = list.get(i).getSoluong();
                        row[4] = list.get(i).getNgayveString();
                        model.addRow(row);
                    }
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());     
            JOptionPane.showMessageDialog(null, "ko tim thay"); 
        }
    }//GEN-LAST:event_search_nhapActionPerformed

    
    // tim hoa don ban hang
    private void search_banActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_banActionPerformed
        String Mon = "-"+txtThang.getText()+"-";
        HoaDon hoaDon;
        ArrayList<HoaDon> list = new ArrayList<HoaDon>();
        try {
            Connection con =getConnection();
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("SELECT * FROM hoadon WHERE ngay_ban LIKE '%"+Mon+"%'");
            while(rs.next()){
                hoaDon = new HoaDon(rs.getString("ma_hd"), rs.getInt("ma_sp"), rs.getFloat("gia_sp"), rs.getInt("so_luong"),rs.getFloat("tong_tien"),rs.getString("ngay_ban"));
                list.add(hoaDon);
                
                DefaultTableModel model = (DefaultTableModel) table_banhang.getModel();
                model.setRowCount(0);
                Object[] row = new Object[6];
                    for(int i=0; i<list.size();i++){
                        row[0] = list.get(i).getMahd();
                        row[1] = list.get(i).getMasp();
                        row[2] = list.get(i).getGiasp();
                        row[3] = list.get(i).getSoluong();
                        row[4] = list.get(i).getTongtien();
                        row[5] = list.get(i).getNgayban();
                        model.addRow(row);
                    }
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());     
            JOptionPane.showMessageDialog(null, "ko tim thay"); 
        }
    }//GEN-LAST:event_search_banActionPerformed

    private void in_dsbanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_in_dsbanActionPerformed
        XSSFWorkbook workbook = new XSSFWorkbook();
        XSSFSheet sheet=  workbook.createSheet("danhsachbanhang");
        XSSFRow row = null ;
        Cell cell=null ;
        // lui xuong 3 hang

        row = sheet.createRow(3);
        
        cell = row.createCell(0, CellType.STRING);
        cell.setCellValue("Mã hóa đơn");
        
        cell = row.createCell(1, CellType.STRING);
        cell.setCellValue("Mã sản phẩm");
        
        
        cell = row.createCell(2, CellType.STRING);
        cell.setCellValue("Giá sản phẩm");
        
        cell = row.createCell(3, CellType.STRING);
        cell.setCellValue("Số lượng");
        
        cell = row.createCell(4, CellType.STRING);
        cell.setCellValue("Tổng tiền");
        
        cell = row.createCell(5, CellType.STRING);
        cell.setCellValue("Ngày bán");
        
        
        for (int i = 0; i<getHoadonList().size() ; i++) {
            // bat dau tu dong thu 4
            row = sheet.createRow(4+i);
            
            cell=row.createCell(0,CellType.STRING);
            cell.setCellValue(getHoadonList().get(i).getMahd());
            
            cell=row.createCell(1,CellType.NUMERIC);
            cell.setCellValue(getHoadonList().get(i).getMasp());
            
            cell=row.createCell(2,CellType.STRING);
            cell.setCellValue(getHoadonList().get(i).getGiasp());
            
            cell=row.createCell(3,CellType.STRING);
            cell.setCellValue(getHoadonList().get(i).getSoluong());
            
            cell=row.createCell(4,CellType.NUMERIC);
            cell.setCellValue(getHoadonList().get(i).getTongtien());
            
            cell=row.createCell(5,CellType.STRING);
            cell.setCellValue(getHoadonList().get(i).getNgayban());
        }
        
        File f = new File("D://danhsachbanhang.xlsx");
        if (!f.exists()) {
            try {
                f.createNewFile();
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage());
            }
        }
        FileOutputStream fos;
        try {
            fos = new FileOutputStream(f);
            workbook.write(fos);
            workbook.close();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(ThongKeForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(ThongKeForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        JOptionPane.showMessageDialog(null, "Xong!");
    }//GEN-LAST:event_in_dsbanActionPerformed

    public Connection getConnection() throws SQLException{
        Connection conn = DriverManager.getConnection("jdbc:mysql://localhost/store","root","");
        return conn;
    }
    
    
    // show danh sach nhap hang

    
    public ArrayList<Nhaphang> getNhaphangList(){
        ArrayList<Nhaphang> nhaphangList = new ArrayList<Nhaphang>();
        Nhaphang nhaphang;
        try {
            Connection con = getConnection();
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("SELECT * FROM nhaphang");
            while (rs.next()) {                
                nhaphang = new Nhaphang(rs.getInt("stt"),rs.getInt("ma_sp"), rs.getString("ten_sp"), rs.getFloat("gia_nhap"), rs.getInt("so_luong"), rs.getString("ngay_ve"));
                nhaphangList.add(nhaphang);
            }
        } catch (SQLException ex) {
            Logger.getLogger(NhapHangForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        return nhaphangList;
    }
    
    public void show_jtable_Nhaphang(){
        ArrayList<Nhaphang> list = getNhaphangList();
        DefaultTableModel model = (DefaultTableModel) table_nhaphang.getModel();
        
        model.setRowCount(0);
        Object[] row = new Object[5];
        for(int i=0; i<list.size();i++){
            //row[0] = list.get(i).getStt();
            row[0] = list.get(i).getMasp();
            row[1] = list.get(i).getTensp();
            row[2] = list.get(i).getGianhap();
            row[3] = list.get(i).getSoluong();
            row[4] = list.get(i).getNgayveString();
            model.addRow(row);
        }
    }
    
    
    // show hoa don ban hang
    
    public ArrayList<HoaDon> getHoadonList(){
        ArrayList<HoaDon> hoadonList = new ArrayList<HoaDon>();
        HoaDon hoaDon;
        try {
            Connection con = getConnection();
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("SELECT * FROM hoadon");
            while(rs.next()){
                hoaDon = new HoaDon(rs.getString("ma_hd"), rs.getInt("ma_sp"), rs.getFloat("gia_sp"), rs.getInt("so_luong"),rs.getFloat("tong_tien"), rs.getString("ngay_ban"));
                hoadonList.add(hoaDon);
            } 
        } catch (SQLException ex) {
            Logger.getLogger(HoaDonForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        return hoadonList;
    }
    public void show_jtable_hoadon(){
        ArrayList<HoaDon> list = getHoadonList();
        DefaultTableModel model = (DefaultTableModel) table_banhang.getModel();
        
        model.setRowCount(0);
        Object[] row = new Object[6];
        for(int i=0;i<list.size();i++){
            row[0] = list.get(i).getMahd();
            row[1] = list.get(i).getMasp();
            row[2] = list.get(i).getGiasp();
            row[3] = list.get(i).getSoluong();
            row[4] = list.get(i).getTongtien();
            row[5] = list.get(i).getNgayban();
            model.addRow(row);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThongKeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThongKeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThongKeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThongKeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ThongKeForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton in_dsban;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton search_ban;
    private javax.swing.JButton search_nhap;
    private javax.swing.JTable table_banhang;
    private javax.swing.JTable table_nhaphang;
    private javax.swing.JTextField txtThang;
    // End of variables declaration//GEN-END:variables
}
